pull_requests:
  do_not_increment_build_number: true

branches:
  except:
  - upstream-dev
  - upstream-master

skip_branch_with_pr: true

image: Visual Studio 2017
shallow_clone: true

clone_folder: C:\projects\tdesktop

test: off

matrix:
  fast_finish: true

cache:
  - c:\tools\vcpkg\installed\

environment:
  qt_dir: C:\Qt\5.9\msvc2017_64

install:
  - cmd: .appveyor\install.cmd

before_build:
  - cmd: .appveyor\before_build.cmd

build_script:
  - ps: .appveyor\build.ps1

after_build:
  - ps: .appveyor\after_build.ps1

artifacts:
  - path: build\kepka.zip
    name: application
  - path: build\pdb.zip
    name: debug-info

notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: RTsEg5GuO6yWL2ha/fURkT9p6pzW/DS/yT0dR8Re7HsHxtQRkzaKU15n7pQdtEPN

deploy:
  provider: GitHub
  auth_token:
    secure: RTsEg5GuO6yWL2ha/fURkT9p6pzW/DS/yT0dR8Re7HsHxtQRkzaKU15n7pQdtEPN
  artifact: application,debug-info
  on:
    appveyor_repo_tag: true
